## Section 1

In [1]:
import numpy as np

In [2]:
L = [1,2,3]
L

[1, 2, 3]

In [3]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [4]:
for i in L:
    print(i)

1
2
3


In [5]:
for i in A:
    print(i)

1
2
3


In [6]:
L.append(4)
L

[1, 2, 3, 4]

In [7]:
L + [5]

[1, 2, 3, 4, 5]

In [8]:
# same as A + 4
A + np.array([4])

array([5, 6, 7])

In [9]:
A**2

array([1, 4, 9], dtype=int32)

## Section 2

In [10]:
a = np.array([1,2])
b = np.array([3,4])

In [11]:
np.dot(a, b)

11

In [12]:
a.dot(b)

11

In [13]:
a @ b

11

In [14]:
a_len, b_len = np.sqrt(np.sum(a**2)), np.sqrt(np.sum(b**2))
a_len, b_len

(2.23606797749979, 5.0)

In [15]:
a_len, b_len = np.linalg.norm(a), np.linalg.norm(b)
a_len, b_len

(2.23606797749979, 5.0)

In [16]:
cos_phy = np.dot(a, b) / a_len / b_len
np.rad2deg(np.arccos(cos_phy))

10.304846468766044

## Speed Test

In [17]:
a, b = np.random.randn(100), np.random.randn(100)

In [18]:
def np_version():
    return np.dot(a,b)
def py_version():
    dot = 0
    for i, j in zip(a, b):
        dot += i*j
    return dot

In [19]:
%timeit np_version()

1.33 µs ± 14 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [20]:
%timeit py_version()

48.3 µs ± 598 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [21]:
np.isclose(np_version(), py_version())

True

## Matrices

In [22]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [23]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [24]:
A[0, 1]

2

In [25]:
B = np.array([[1,2,3],[4,5,6]])
A.dot(B)  # matrix multiplication

array([[ 9, 12, 15],
       [19, 26, 33]])

## Linear Systems

In [29]:
# x1 + x2 = 2000
# 1.5x1 + 4x2 = 5050

A = np.array([[1,1], [1.5,4]])
b = np.array([2000, 5050])

x = np.linalg.solve(A, b)
x

array([1180.,  820.])

## Generating data

In [30]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.full((2, 3), 10.0)

array([[10., 10., 10.],
       [10., 10., 10.]])

In [34]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.random.random()

0.4361352498816464

In [36]:
np.random.random((2, 3))

array([[0.33518451, 0.04461777, 0.39030265],
       [0.49269681, 0.7736918 , 0.92026787]])

In [37]:
np.random.randn(2, 3)

array([[ 1.73236483,  0.70319129,  0.11511238],
       [-1.74738393, -0.32059404, -0.7060415 ]])

In [39]:
R = np.random.randn(100000)
R.mean(), R.var(), R.std()

(-0.0014814307706581217, 0.995556575232439, 0.9977758141147935)

In [40]:
R = np.random.randn(100000, 3)
R.mean(axis=0)

array([ 0.00093423, -0.00473792, -0.00097344])

In [41]:
np.cov(R.T)

array([[ 1.00033551e+00, -2.44476628e-03,  5.30390194e-04],
       [-2.44476628e-03,  9.99173309e-01, -5.10312636e-03],
       [ 5.30390194e-04, -5.10312636e-03,  1.00156543e+00]])

In [42]:
np.random.randint(0, 100, size=(5,5))

array([[40, 47, 37, 22, 71],
       [94, 42, 85, 27, 64],
       [84, 22, 80, 59, 71],
       [77, 72, 59, 34, 62],
       [14, 77, 95, 65, 75]])

In [47]:
np.random.choice(list(range(10)), size=8, replace=False)

array([0, 5, 6, 8, 4, 2, 3, 7])

## Exercise

In [86]:
l_a = [
    [1.0,2.0,3.0],
    [4.0,5.0,6.0]
]
l_b = [
    [1.0,2.0,3.0,4.0],
    [2.0,3.0,4.0,5.0],
    [3.0,4.0,5.0,6.0]
]
a_a = np.array(l_a)
a_b = np.array(l_b)

In [87]:
def list_dot(a, b):
    n1 = len(a[0])
    n2 = len(b)
    if n1 != n2:
        raise Exception("Wrong matrix sizes")
    m = len(a)
    p = len(b[0])
    return [[sum(a[i][k]*b[k][j] for k in range(n1)) for j in range(p)] for i in range(m)]

In [88]:
%timeit list_dot(l_a, l_b)

11.4 µs ± 36.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [89]:
%timeit a_a.dot(a_b)

814 ns ± 1.14 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [90]:
np.allclose(list_dot(l_a, l_b), a_a.dot(a_b))

True