## Section 1

In [1]:
import numpy as np

In [2]:
L = [1,2,3]
L

[1, 2, 3]

In [3]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [4]:
for i in L:
    print(i)

1
2
3


In [5]:
for i in A:
    print(i)

1
2
3


In [6]:
L.append(4)
L

[1, 2, 3, 4]

In [7]:
L + [5]

[1, 2, 3, 4, 5]

In [9]:
# same as A + 4
A + np.array([4])

array([5, 6, 7])

In [10]:
A**2

array([1, 4, 9], dtype=int32)

## Section 2

In [11]:
a = np.array([1,2])
b = np.array([3,4])

In [13]:
np.dot(a, b)

11

In [14]:
a.dot(b)

11

In [15]:
a @ b

11

In [20]:
a_len, b_len = np.sqrt(np.sum(a**2)), np.sqrt(np.sum(b**2))
a_len, b_len

(2.23606797749979, 5.0)

In [22]:
a_len, b_len = np.linalg.norm(a), np.linalg.norm(b)
a_len, b_len

(2.23606797749979, 5.0)

In [21]:
cos_phy = np.dot(a, b) / a_len / b_len
np.rad2deg(np.arccos(cos_phy))

10.304846468766044

## Speed Test

In [24]:
a, b = np.random.randn(100), np.random.randn(100)

In [25]:
def np_version():
    return np.dot(a,b)
def py_version():
    dot = 0
    for i, j in zip(a, b):
        dot += i*j
    return dot

In [27]:
%timeit np_version()

1.32 µs ± 4.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [28]:
%timeit py_version()

47.4 µs ± 298 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [29]:
np.isclose(np_version(), py_version())

True